<html>
<head>
    <meta charset="utf-8">
    <title><?=$this->translate('L_WEB_SCOUT')?> | <?=$this->translate('L_REPORT')?></title>
    <link rel="stylesheet" href="/js/jquery-ui.min.css">
    <link rel="stylesheet" href="/js/jquery-ui.theme.min.css">
    <link rel="stylesheet" href="/js/jquery-ui.structure.min.css">
    <link rel="stylesheet" href="/style.css">

    <script src="/js/jquery.js"></script>
    <script src="/js/jquery-ui.min.js"></script>
    <script src="/js/functions.js"></script>

</head>
<body>
<?php echo $this->layout()->content ?>
</body>
</html>
