<table width="80%" border="1">
    <tr>
        <th colspan="2"><?=$this->translate('L_HOSTS')?></th>
    </tr>
    <tr>
        <th><?=$this->translate('L_NAME')?></th>
        <th><?=$this->translate('L_DESCRIPTION')?></th>
    </tr>
    <? foreach($this->hosts as $host): ?>
        <tr>
            <td><a href="/index/host/host/<?=$host['id']?>/"><?=$host['name']?></a></td>
            <td><?=$host['descr']?></td>
        </tr>
    <? endforeach ?>

</table>