<?
$translates = [
    'cms' => $this->translate('L_SCRIPTS'),
    'robots_txt' => '/robots.txt',
    'ns' => $this->translate('L_DOMAINS'),
    'backups' => $this->translate('L_BACKUPS'),
    'dafs_dirs' => $this->translate('L_FOUND_FILES'),
    'dafs_files' => $this->translate('L_FOUND_DIRS'),
    'powered_by' => $this->translate('L_POWERED_BY_PHRASE'),
    'encodings' => $this->translate('L_ENCODINGS'),
    'sitemap' => $this->translate('L_SITEMAP'),
    'ns_always_true' => $this->translate('L_DNS_ALWAYS_TRUE'),
    'nf' => $this->translate('L_404_RESPONSE'),
    'headers' => $this->translate('L_INTEREST_HEADERS'),
]
?>
<div id="tabs">
    <ul>
        <li><a href="#tabs-1"><?=$this->translate('L_URL_MAP')?></a></li>
        <li><a href="#tabs-2"><?=$this->translate('L_INFO')?></a></li>
        <li><a href="#tabs-3"><?=$this->translate('L_REQUESTS')?></a></li>
    </ul>
        <div id="tabs-1">
            <div id="sitemap-<?=$this->host['id']?>-0">
                <div onclick="loadSitemap(<?=$this->host['id']?>, 0, 1)"><?=$this->host['name']?></div><br/>
                <div id="sitemap-content-<?=$this->host['id']?>-0"></div>
            </div>
        </div>
        <div id="tabs-2">
            <?foreach ($this->hostInfo as $field => $value):?>
                <table width="80%" border="1">
                    <tr>
                        <td width="40%" valign="top"><?=$translates[$field]?></td>
                        <td valign="top">
                <?
                    switch($field) {
                        case 'cms':
                            if ($value) {
                                foreach ($value as $v) {
                                    print "{$v->name}, {$v->percent}%<br />";
                                }
                            } else {
                                print $this->translate('L_NO_INFO');
                            }
                            break;
                        case 'robots_txt':
                            if ($value) {
                                print $this->translate('L_YES_2');
                            } else {
                                print $this->translate('L_NOT_FOUND');
                            }
                            break;
                        case 'ns_always_true':
                            if (json_decode($value)) {
                                print $this->translate('L_YES_1');
                            } else {
                                print $this->translate('L_NO');
                            }
                            break;
                        case 'nf':
                            print "{$this->translate('L_FILES')}: {$value->files}<br />";
                            print "{$this->translate('L_DIRS')}: {$value->dirs} <br />";
                            break;
                        case 'powered_by':
                            if ($value) {
                                print implode("<br />", array_map('htmlspecialchars', $value));
                            } else {
                                print $this->translate('L_NOT_FOUND');
                            }
                            break;
                        case 'headers':
                            if ($value) {
                                foreach ($value as $v) {
                                    print "{$v->name}: {$v->value}<br />";
                                }
                            } else {
                                print $this->translate('L_NOT_FOUND');
                            }
                            break;
                        case 'dafs_files':
                        case 'dafs_dirs':
                        case 'backups':
                            if ($value) {
                                foreach ($value as $v) {
                                    print "({$v->code}) {$v->url}<br />";
                                }
                            } else {
                                print $this->translate('L_NOT_FOUND');
                            }
                            break;
                        case 'encodings':
                            print "HTTP: {$value->http}<br />HTML: {$value->html}";
                            break;
                        case 'sitemap':
                            if ($value) {
                                print "{$this->translate('L_URL_ADDED')}: {$value->added}<br />";
                                print implode("<br/>", $value->links);
                            } else {
                                print $this->translate('L_NOT_FOUND');
                            }
                            break;
                        case 'ns':
                            if ($value) {
                                foreach ($value as $v) {
                                    print "({$v->ip}) {$v->name}<br />";
                                }
                            } else {
                                print $this->translate('L_NOT_FOUND');
                            }
                            break;
                    }
                ?>
                        </td>
                    </tr>
                </table>
            <?endforeach?>
        </div>
        <div id="tabs-3">
            <table width="100%" border="1">
                <tr>
                    <th colspan="6"><?=$this->translate('L_REQUESTS')?></th>
                </tr>
                <tr>
                    <th><?=$this->translate('L_METHOD')?></th>
                    <th><?=$this->translate('L_PROTOCOL')?></th>
                    <th><?=$this->translate('L_HEADERS')?></th>
                    <th><?=$this->translate('L_URL')?></th>
                    <th><?=$this->translate('L_FINDER')?></th>
                    <th><?=$this->translate('L_DESCRIPTION')?></th>
                </tr>
                <?foreach ($this->requests as $request):?>
                <tr>
                    <td>
                        <?=$request->method?>
                    </td>
                    <td>
                        <?=$request->protocol?>
                    </td>
                    <td>
                        <?
                            $headers = json_decode($request->headers);
                            foreach (get_object_vars($headers) as $header => $value) {
                                #print "$header: {$headers->$header}<br/>";
                                print "$header: $value<br/>";
                            }
                        ?>
                    </td>
                    <td>
                        <? echo (strlen($request->params) ? "{$request->path}?{$request->params}" : $request->path) ?>
                    </td>
                    <td>
                        <?=$request->founder?>
                    </td>
                    <td>
                        <?=$request->comment?>
                    </td>
                </tr>
                <?endforeach?>
            </table>
        </div>
</div>
<script>

    $(function() {
        $( "#tabs" ).tabs();
        loadSitemap(<?=$this->host['id']?>, 0, 1)
    });

</script>

