<table width="80%" border="1">
    <tr>
        <th colspan="2"><?=$this->translate('L_PROJECTS')?></th>
    </tr>
    <tr>
        <th><?=$this->translate('L_NAME')?></th>
        <th><?=$this->translate('L_DESCRIPTION')?></th>
    </tr>
        <? foreach($this->projects as $project): ?>
    <tr>
        <td><a href="/index/hosts/project/<?=$project['id']?>/"><?=$project['name']?></a></td>
        <td><?=$project['descr']?></td>
    </tr>
        <? endforeach ?>

</table>