<?php
return [
    'L_WEB_SCOUT' => 'Web-Scout',
    'L_REPORT' => 'Report',
    'L_NAME' => 'Name',
    'L_DESCRIPTION' => 'Description',
    'L_PROJECTS' => 'Projects',
    'L_HOSTS' => 'Hosts',
    'L_SCRIPTS' => 'Scripts',
    'L_DOMAINS' => 'Domain names',
    'L_BACKUPS' => 'Backups',
    'L_FOUND_FILES' => 'Found files',
    'L_FOUND_DIRS' => 'Found dirs',
    'L_POWERED_BY_PHRASE' => 'Phrase "Powered by"',
    'L_ENCODINGS' => 'Encodings',
    'L_SITEMAP' => 'Sitemap',
    'L_DNS_ALWAYS_TRUE' => 'DNS return IP on request all random domains',
    'L_404_RESPONSE' => 'Response code when requested object not exists (404)',
    'L_INTEREST_HEADERS' => 'Interest headers',
    'L_URL_MAP' => 'URL map',
    'L_INFO' => 'Information',
    'L_REQUESTS' => 'Requests',
    'L_NOT_FOUND' => 'Not found',
    'L_NO_INFO' => 'No information',
    'L_YES_1' => 'Yes',
    'L_YES_2' => 'Yes',
    'L_NO' => 'No',
    'L_FILES' => 'Files',
    'L_DIRS' => 'Dirs',
    'L_URL_ADDED' => 'URLs added',
    'L_METHOD' => 'Method',
    'L_PROTOCOL' => 'Protocol',
    'L_HEADERS' => 'Headers',
    'L_URL' => 'URL',
    'L_FINDER' => 'Finder',
];
