<?php
return [
    'L_WEB_SCOUT' => 'Веб-Скаут',
    'L_REPORT' => 'Отчёт',
    'L_NAME' => 'Название',
    'L_DESCRIPTION' => 'Описание',
    'L_PROJECTS' => 'Проекты',
    'L_HOSTS' => 'Хосты',
    'L_SCRIPTS' => 'Скрипты',
    'L_DOMAINS' => 'Доменные имена',
    'L_BACKUPS' => 'Резервные копии',
    'L_FOUND_FILES' => 'Найденные файлы',
    'L_FOUND_DIRS' => 'Найденные директории',
    'L_POWERED_BY_PHRASE' => 'Фраза "Powered by"',
    'L_ENCODINGS' => 'Кодировки',
    'L_SITEMAP' => 'Карта сайта',
    'L_DNS_ALWAYS_TRUE' => 'IP возвращается на запрос любого поддомена',
    'L_404_RESPONSE' => 'Код ответа при несуществующем объекте',
    'L_INTEREST_HEADERS' => 'Интересные заголовки',
    'L_URL_MAP' => 'Карта URL',
    'L_INFO' => 'Информация',
    'L_REQUESTS' => 'Запросы',
    'L_NOT_FOUND' => 'Не найдено',
    'L_NO_INFO' => 'Нет информации',
    'L_YES_1' => 'Да',
    'L_YES_2' => 'Есть',
    'L_NO' => 'Нет',
    'L_FILES' => 'Файлы',
    'L_DIRS' => 'Директории',
    'L_URL_ADDED' => 'Добавлено URL',
    'L_METHOD' => 'Метод',
    'L_PROTOCOL' => 'Протокол',
    'L_HEADERS' => 'Заголовки',
    'L_URL' => 'URL',
    'L_FINDER' => 'Нашёл',
];
